- name: Reproduce ouptuts with JDLL 0.5.5-SNAPSHOT (keras_hdf5)
  status: failed
  error: unable to perform tests
  traceback: "java.lang.IllegalArgumentException: The axes order introduced has to\
    \ correspond to the same number of dimenensions that the NDArray has. In this\
    \ case the axes order is specfied for 4 dimensions while the array has 2 dimensions.\n\
    \tat io.bioimage.modelrunner.tensor.Tensor.checkDims(Tensor.java:613)\n\tat io.bioimage.modelrunner.tensor.Tensor.<init>(Tensor.java:111)\n\
    \tat io.bioimage.modelrunner.tensor.Tensor.build(Tensor.java:149)\n\tat io.bioimage.modelrunner.ci.ContinuousIntegration.testModelInference(ContinuousIntegration.java:338)\n\
    \tat io.bioimage.modelrunner.ci.ContinuousIntegration.testResource(ContinuousIntegration.java:254)\n\
    \tat io.bioimage.modelrunner.ci.ContinuousIntegration.runTests(ContinuousIntegration.java:157)\n\
    \tat io.bioimage.modelrunner.ci.ContinuousIntegration.main(ContinuousIntegration.java:78)\n"
  source_name: /home/runner/work/icy-bioimage-io/icy-bioimage-io/bioimageio-gh-pages/rdfs/10.5281/zenodo.6865412/6919253/rdf.yaml
  JDLL_VERSION: 0.5.5-SNAPSHOT
